[character]
success_symbol = 'ğŸŒ»'
error_symbol = 'âŒ'
#success_symbol = '[\$](bold green)'
#error_symbol = '[\$](bold red)'

[directory]
style = 'fg:75'

[git_branch]
symbol = 'ğŸŒµ'
style = 'fg:208'

[git_status]
style = 'fg:40'

[rust]
disabled = true
